import { l, pick, type L, type Lang, type Scenario } from './content';
import { addressedCharacter, inferTopic, variantFor, availableStoryEvents, type TopicId, type VariantId } from './story';
import type { Message, Reply } from './engine';
import type { RoomContext } from './room';
import { actionEvidence, type DinnerContext } from './drama';

type Topic = { owner:number; questions:L[]; details:L[]; proposal:L; boundary:L };
const topics:Record<TopicId,Topic>={
  toast:{owner:0,questions:[l('就这一杯，也不行？你是今天不喝，还是以后都不喝？','Not even this one glass? Is it tonight, or do you never drink?'),l('不喝我听见了。可这场合作，你准备怎么向林姐表达？','I heard you won’t drink. How do you want to acknowledge this partnership to Ms. Lin?'),l('杯子先放一边。感谢的话，你愿意自己跟林姐讲吗？','Leave the glass aside. Will you say the thank-you to Ms. Lin yourself?')],details:[l('我想听的是你重视这次合作，不是让别人替你说。','I want to hear that this partnership matters to you, in your own words.'),l('林姐今天为续约来的。我希望这一桌别让她觉得受了冷落。','Ms. Lin came for the renewal. I don’t want her to feel overlooked.')],proposal:l('茶可以。你跟林姐说吧，我听着。','Tea is an option. Say it to Ms. Lin; I’m listening.'),boundary:l('今天不喝，我听到了。那这杯先不劝，你把想说的话讲完。','I hear you’re not drinking tonight. Leave the glass, then. Finish what you wanted to say.')},
  scope:{owner:1,questions:[l('那你把原来答应的和新增的分开说。报表算在哪边？','Separate what was originally agreed from what is new. Where does the report fit?'),l('如果报表放下一版，这次先验收哪些功能？','If the report waits for the next version, which features can we accept now?'),l('我能确认客户这边的优先级，测试能不能过还得你们说明。','I can confirm the client priorities. Your side still needs to account for the tests.')],details:[l('新增的是报表。原范围先交还是一起交，我还没有确认。','The report is new. I haven’t confirmed whether it ships with the original scope.'),l('我关心能实际验收的内容，不是单说“会尽力”。','I need something we can actually accept, not just “we’ll try.”')],proposal:l('可以先列范围。原功能和新增报表分开，今天谁把清单发给我？','We can start with a scope list. Separate the original features and new report. Who will send it today?'),boundary:l('你不接新增范围，我知道了。那原范围能交到什么程度？','I understand you aren’t taking on the extra scope. What can you deliver from the original scope?')},
  deadline:{owner:1,questions:[l('周三是我现在要报的窗口。两项测试不过，最早什么时候能再判断？','Wednesday is the window I need to report. If those tests fail, when can we reassess?'),l('明早看结果可以。谁给测试结果，谁决定能不能上线？','We can review tomorrow morning. Who supplies the tests, and who decides whether to launch?'),l('如果结果还没过，你希望我向客户报延期，还是缩小这次范围？','If they still fail, should I tell the client we’re delaying or reducing this release?')],details:[l('现在是两项测试没过，新增报表的范围也没确认。周三还只是目标。','Two tests are failing, and the new report’s scope is unconfirmed. Wednesday is still a target.'),l('具体失败项要小周补充，我不能替测试下结论。','Zhou needs to explain the failing checks. I can’t decide the test result for them.')],proposal:l('先按你说的条件评估，不把它写成已经保证。测试结果谁来确认？','We can assess those conditions without calling it guaranteed. Who will confirm the test results?'),boundary:l('不能保证周三，我听清了。那请给我一个下一次确认的时间。','I hear that you can’t guarantee Wednesday. Give me a time for the next confirmation.')},
  introduction:{owner:0,questions:[l('我只是想介绍认识。你是不想看照片，还是不想安排见面？','I want to introduce you. Do you not want the photo, or do you not want a meeting arranged?'),l('你不想见，我听到了。那我怎么跟介绍人回话？','I hear you don’t want to meet. What should I tell the person who introduced them?'),l('那这次我先不替你约。以后有人问，我也说你自己决定？','I won’t book this meeting for you. If someone asks later, should I say you decide for yourself?')],details:[l('还没有约见面。是我觉得可以认识，想问你的意思。','No meeting is arranged. I thought an introduction might work and wanted your answer.'),l('看照片、加联系方式和见面，你可以分开说，我别会错意。','Tell me separately about the photo, contact and meeting, so I don’t misunderstand.')],proposal:l('你把愿意的那一步说清楚。后面的事，我不能当你也答应了。','Be clear about the one step you’re willing to take. I can’t treat the rest as agreed.'),boundary:l('你这次不考虑，我听到了。我还觉得可惜，但不替你约见面。','I hear you aren’t interested this time. I still think it’s a shame, but I won’t arrange the meeting.')},
  privacy:{owner:1,questions:[l('我以为告诉大姨没关系。你介意的是工资，还是工作变动也不能转述？','I thought telling your aunt was okay. Is it your pay you want private, or the change at work too?'),l('那我以后先问你。已经跟大姨说的那句，你希望我怎么补充？','I can ask first next time. What should I add to what I already told your aunt?'),l('我也想知道你过得怎样。哪些你愿意告诉我，但只留在我们之间？','I still want to know how you are. What would you share with me if it stays between us?')],details:[l('我告诉大姨的是你工作有变动，没有问过你。其他细节我也不清楚。','I told your aunt something changed at work without asking. I don’t know the other details.'),l('我没有替你确认工资，也不能替你解释工作安排。','I haven’t confirmed your pay and can’t explain your work arrangements for you.')],proposal:l('你说的范围我可以照着来。涉及你的消息，我先问一句再转述，可以吗？','I can follow that boundary. Shall I ask before passing on news about you?'),boundary:l('你不想继续讲细节，我听到了。但已经说出去的那条，我们怎么处理？','I hear you don’t want to share more detail. How should we deal with what has already been shared?')},
  autonomy:{owner:0,questions:[l('你想自己决定，我听到了。那这件事，今天你愿意说到哪一步？','I hear you want to decide. How far do you want to discuss this today?'),l('我可以不替你定时间。不过以后问一句近况，也要先问能不能问吗？','I can leave the timing to you. Do I need to ask permission even to ask how you are?'),l('那就分清：可以关心，不能替你答应。你说的是这个意思吗？','So caring is welcome, but agreeing on your behalf isn’t. Is that what you mean?')],details:[l('我确实想替你张罗，但还没有你的明确答应。','I do want to arrange things, but I don’t have your explicit agreement.'),l('你只答应哪一件，我们就只谈那一件。','If you agree to one thing, let’s discuss only that thing.')],proposal:l('具体哪些能问、哪些不能替你安排，你再说一遍，我免得会错意。','Say which things we can ask and which we cannot arrange for you, so I don’t misread it.'),boundary:l('我不替你答应。可关心你的话，我还是想有机会说。','I won’t agree for you. But I still want room to express concern.')},
  credit:{owner:0,questions:[l('代码和设计可以写。我的汇报、联络也做了，准备怎样一起写？','We can name code and design. I did the presentation and contacts too. How do we write both?'),l('别只说每个人都有功劳。你把那句文案说出来，大家核对。','Don’t just say everyone contributed. Give us the actual caption to check.'),l('这句话谁来改，发之前让哪些人确认？','Who edits that sentence, and who checks before it goes out?')],details:[l('我做了汇报和联络，代码和设计不是我一个人做的。','I handled the presentation and contacts. I didn’t make the code and design alone.'),l('照片还没发，文案也还没定。现在能谈具体写法。','The photo hasn’t gone out and the caption isn’t final. We can discuss wording now.')],proposal:l('你的写法可以放到群里核对。不过我的汇报和联络也要写进去。','Your wording can go to the group for review. My presentation and contacts must be included too.'),boundary:l('你不同意只写“带队拿下”，我听到了。那换哪一句，能把分工写准确？','I hear you reject just “led the team to victory.” What sentence records the roles accurately?')},
  evidence:{owner:2,questions:[l('代码提交我能整理。设计版本还得小月自己补，不能我替她写。','I can collect the code commits. Yue needs to add the design versions; I can’t write for her.'),l('整理好先发群里。是每个人确认自己的部分，还是还要对照原文案？','I’ll share the records first. Does everyone confirm their part, or also compare the caption?'),l('记录能证明做过什么，但文案怎么发，还得学长当场确认。','Records show who did what, but Xu still needs to confirm what gets posted.')],details:[l('我和你都有核心代码的提交。具体次数我得查，不能现在瞎报。','We both committed core code. I’d have to check the counts, not guess now.'),l('我只能确认代码那部分。设计交付由小月确认，汇报由学长确认。','I can confirm code only. Yue confirms design, Xu confirms the presentation.')],proposal:l('我可以先整理代码记录。整理出来不等于大家同意文案，发布前还得各自确认。','I can collect the code records first. That doesn’t mean everyone accepts the caption; each person still checks it.'),boundary:l('不想现在定文案也可以。你希望先核对哪一项？','We don’t have to settle the caption now. What should we check first?')},
  workload:{owner:0,questions:[l('那演示、海报、答辩分开谈。你能接哪一项，另外两项谁来确认？','Let’s separate demo, poster and Q&A. Which can you take, and who confirms the other two?'),l('不能只把任务推给小月和阿凯。他们各自还有多少时间，得问本人。','We can’t just hand it to Yue and Kai. We need to ask what time each has.'),l('周五之前先保哪一项？如果来不及，全队要一起删掉什么？','What comes first before Friday? If time runs out, what will the team drop?')],details:[l('周五要展示，但演示、海报和答辩都还没有分工。','The showcase is Friday, but demo, poster and Q&A are not assigned yet.'),l('熟悉代码不等于三项都能接，这个我听见了。现在谈每项需要的时间。','Knowing the code doesn’t mean you can take all three. Let’s discuss how much time each needs.')],proposal:l('你先确认自己能接的部分。其他人的任务，让他们自己说，不在这里替他们答应。','Confirm only the part you can take. Let the others accept their own tasks.'),boundary:l('你不接全部，我听到了。那剩下的事，我们逐项分，不再一句话都压给你。','I hear you won’t take everything. Let’s divide the remaining work item by item.')},
};

const otherVoice:Record<Scenario['id'],L[]>={
 work:[l('我不能替测试保证结果。你要我确认的是范围、资源，还是跟客户重新说时间？','I can’t guarantee the tests. Do you need me to confirm scope, resources or a new date with the client?'),l('喝不喝我不替你决定。我关心的是范围和验收，你想先确认哪一项？','I won’t decide whether you drink. I care about scope and acceptance. Which should we confirm first?'),l('我可以说明我们做过的测试，但不能替你承诺日期。你想让我补充哪一项？','I can explain the tests we ran, but can’t promise a date for you. What should I add?')],
 family:[l('我听着。你是请我别再追问，还是要我帮你转告别人？','I’m listening. Are you asking me to stop questioning, or to tell someone something?'),l('我想听你自己的意思。你愿意告诉我到哪一步，哪些先不谈？','I want your own answer. What would you tell me, and what should we leave aside?'),l('我听见的是你还没有答应。先让你把话讲完，别替你往后安排。','What I heard is that you haven’t agreed. Let you finish before anyone arranges the next step.')],
 school:[l('我能确认自己的汇报职责，不能替他们答应。你想让我改文案，还是重新分工？','I can confirm my presentation role, not agree for them. Do you want a caption change or different assignments?'),l('设计是我做的。我能确认设计那部分，代码和演示要问你和阿凯。','I did the design. I can confirm that part; you and Kai need to confirm code and demo.'),l('代码记录我能一起核对。至于新的任务，我得先看时间，不能现在全接。','I can check the code records with you. For new tasks I need to check my time before agreeing.')],
};

export type ScriptContext={ history?:Message[]; variantId?:VariantId; targetId?:string; maxTurns?:number };
/** An explicit offline rehearsal, driven by topic and prior evidence rather than a turn-number script. */
export function continueScript(scene:Scenario,text:string,turn:number,lang:Lang,room:RoomContext|undefined,dinner:DinnerContext|undefined,context:ScriptContext={}):Reply {
 const history=context.history??[],variant=variantFor(scene.id,context.variantId);
 const previous=[...history].reverse().find(m=>m.role==='npc');
 const current=previous?.story?.topic??(dinner?.eventId==='work-deadline'?'deadline':dinner?.eventId==='family-phone'?'introduction':dinner?.eventId==='school-photo'?'credit':variant.topic);
 const topic=inferTopic(scene.id,text,current),thread=topics[topic];
 const target=addressedCharacter(scene,text,context.targetId);
 const actor=target?scene.characters.findIndex(c=>c.id===target):thread.owner;
 const count=history.filter(m=>m.role==='npc'&&m.story?.topic===topic).length;
 const attack=/闭嘴|滚|有病|放屁|shut up|idiot|stupid/i.test(text);
 const question=/[?？]|哪|为什么|多少|怎样|怎么|\b(what|why|when|how|which)\b/i.test(text);
 const refusal=/不喝|不接|不想|不愿|不答应|不同意|不能|不要|不见|拒绝|don[’']?t|won[’']?t|can[’']?t|cannot|not agree|will not/i.test(text);
 const proposal=/先.{1,20}再|如果|可以|建议|我能|我负责|我来|愿意|明早|今晚|群里|核对|分开|茶|\b(if|can|could|tea|review|tomorrow|tonight)\b/i.test(text);
 let line=actor===thread.owner?thread.questions[Math.min(count,thread.questions.length-1)]:otherVoice[scene.id][actor];
 if(actor===thread.owner){
   if(question)line=thread.details[count%thread.details.length];
   else if(proposal)line=thread.proposal;
   else if(refusal&&count>0)line=thread.boundary;
 }
 if(attack)line=l('你这样说，我没法接着谈。你不同意的具体是哪件事？','I can’t continue with that tone. What specifically do you disagree with?');
 if(/抱歉|对不起|刚才.*急|sorry|apolog/i.test(text))line=l('刚才那句我听见了。我们接着说事情，你想先改哪一点？','I heard that. Let’s return to the issue. What do you want to change first?');
 if(/离开|先走|不聊了|结束|leave now|stop here|end this/i.test(text))line=l('好，今天先停。还没说定的事，我不会当作你答应了。','All right, we’ll stop here. I won’t count anything unresolved as your agreement.');
 const health=/开车|过敏|服药|吃药|身体|drive|driving|allerg|medicat|health/i.test(text);
 const priorHealth=history.some(m=>m.role==='user'&&/开车|过敏|服药|吃药|drive|driving|allerg|medicat/i.test(m.text));
 if(topic==='toast'&&!attack&&(health||priorHealth))line=actor===0?l('那酒就不劝了。你想用茶敬，还是先把话说完？','Then I won’t push the alcohol. Do you want to toast with tea or finish speaking first?'):l('不喝酒的原因你已经说清楚了。这杯不需要再解释，你接着说。','You’ve explained why you aren’t drinking. You don’t need to justify the glass again. Go on.');
 const fresh=dinner?.previous.find(r=>r.eventId===dinner.eventId&&r.choice===dinner.choice&&r.turn===turn-1);
 // Respond to the choice only when the player has not supplied a more specific subject.
 if(fresh&&!attack&&!question&&!proposal&&!refusal&&!health&&/^(嗯[？?。]?|哦|啊[？?]?|ok|hmm)[.!?]?$/i.test(text.trim())){
   line=l(`刚才你${actionEvidence(fresh,'zh').action}，我看到了。你想接着说哪一件事？`,`I saw you ${actionEvidence(fresh,'en').action.toLowerCase()}. What do you want to discuss next?`);
 }
 let spoken=pick(line,lang);
 // Once a line has been heard, ask about the player's actual latest words, not a recycled ending.
 if(!attack&&previous?.text===spoken){
   const quote=text.slice(0,80);
   spoken=pick(l(`你说“${quote}”。具体希望我接下来做哪一步？`,`You said “${quote}”. What specific next step are you asking me to take?`),lang);
 }
 const who=scene.characters[actor];
 const gesture=attack?'fold':'lean';
 if(topic==='toast'&&proposal&&!/茶|tea/i.test(text)&&!health&&!priorHealth&&!attack)spoken=pick(l('你想表达的我听到了。你是要把酒先放下，直接跟林姐说合作的事？','I hear what you want to express. Do you want to leave the drink and speak to Ms. Lin about the partnership?'),lang);
 const cue=pick(attack?l(`${who.name.zh}抱起手臂看向你。`,`${who.name.en} folds their arms and looks at you.`):l(`${who.name.zh}朝你倾身，等你接话。`,`${who.name.en} leans toward you and waits.`),lang);
 const spatial=room?.posture==='standing'?pick(room.zone==='table'?l('你站在桌边回答，大家抬头看向你。','You answer standing beside the table. They look up at you.'):l('你在包厢另一侧回答，桌上的人转向你。','You answer from across the room. The table turns toward you.'),lang)+' ':'';
 if(!fresh&&room?.posture==='standing'&&room.zone!=='table'&&/^(hello|hi|嗯[？?]?|啊[？?]?)$/i.test(text.trim()))spoken=pick(l('我听见你了。你想先离席，还是继续刚才的话？','I hear you. Do you want to leave, or continue what we were discussing?'),lang);
 const available=availableStoryEvents(variant,turn,history,text,[dinner?.eventId,...(dinner?.previous.map(r=>r.eventId)??[])].filter((id):id is NonNullable<typeof id>=>!!id));
 const desired=scene.id==='work'&&topic==='deadline'&&topic!==current?'work-deadline':scene.id==='family'&&/照片|手机|photo|phone/i.test(text)&&!refusal?'family-phone':scene.id==='school'&&/合照|拍照|photo|picture/i.test(text)&&!refusal?'school-photo':undefined;
 const event=desired&&available.includes(desired)?desired:undefined;
 if(event==='family-phone')spoken=pick(l('照片在妈妈手机里。先看不代表答应见面，你想现在看吗？','The photo is on Mom’s phone. Looking doesn’t mean agreeing to meet. Would you like to look now?'),lang);
 if(event==='school-photo')spoken=pick(l('照片可以等文案核对后再发。现在要不要先一起入镜？','We can hold the photo until the caption is checked. Shall we all get in the frame now?'),lang);
 return {speakerId:who.id,text:spoken,cue:spatial+cue,story:{topic,...(event?{event}: {})},reactions:scene.characters.map((c,i)=>({characterId:c.id,emotion:i===actor?(attack?'annoyed':'pressing'):i===0?'pressing':'thinking',gesture:i===actor?gesture:'idle'}))};
}
