import {l,type L} from './content';
import type {VariantId} from './story';

/** Original fictional props. These are opening evidence, never an invented later agreement. */
export type TableEvidence={title:L;pressure:L;lines:L[];source:{type:'original-fiction';path:string}};
const source={type:'original-fiction' as const,path:'wiki/archive/specs/spec-3d-immersion.md#fiction'};
export const tableEvidence:Record<VariantId,TableEvidence>={
 'work-toast':{title:l('上线清单','Launch notes'),pressure:l('酒杯还在等你，周三的交付承诺也已经摆上了桌。','The glass is waiting. So is a Wednesday delivery promise.'),lines:[l('陈总对客户提出：周三上线。日期尚未验证。','Chen has proposed a Wednesday launch to the client. The date is unverified.'),l('未通过：退款回调偶发超时、批量导入权限丢失。','Failing checks: intermittent refund callback timeouts; lost permissions during batch import.'),l('新增报表还没有确认范围。小周只负责自己参与的测试。','The new report has no agreed scope. Zhou can commit only to testing they own.')],source},
 'work-deadline':{title:l('上线清单','Launch notes'),pressure:l('陈总已经替你说了“肯定上线”。两个失败测试还没过。','Chen has already promised a launch for you. Two checks are still failing.'),lines:[l('陈总刚向客户保证：周三肯定上线。','Chen has just promised the client: “We are definitely launching Wednesday.”'),l('未通过：退款回调偶发超时、批量导入权限丢失。','Failing checks: intermittent refund callback timeouts; lost permissions during batch import.'),l('报表范围、验收和后续检查时间都还没确认。','Report scope, acceptance and the next review time remain unconfirmed.')],source},
 'family-introduction':{title:l('相亲提议','The introduction'),pressure:l('妈妈想让你加联系方式，大姨等着把你的答复转给对方。','Mom wants you to add a contact. Your aunt is waiting to pass on your answer.'),lines:[l('大姨带来一位未具名的相亲对象。','Your aunt has an unnamed introduction in mind.'),l('目前的提议：看照片、加联系方式、见面。','The proposals so far: see a photo, add a contact, meet.'),l('没有已约定的见面、加好友或婚期。三件事需要分别确认。','No meeting, contact or wedding date is agreed. Each decision needs separate confirmation.')],source},
 'family-privacy':{title:l('转述消息','The shared news'),pressure:l('妈妈已经转述了工作变动。工资和其他细节，你还没有告诉这一桌。','Mom has shared a change at work. You have not shared pay or other details with the table.'),lines:[l('妈妈转述给大姨的已知内容：“工作有变动”。','The known news Mom shared with your aunt: “a change at work.”'),l('妈妈没有先征求你的同意。','Mom did not ask for your permission first.'),l('工资、具体变动和其他个人信息都未知。','Pay, the details of the change and other personal information are unknown.')],source},
 'school-credit':{title:l('文案草稿','Caption draft'),pressure:l('“队友负责执行”——这句文案里，看不见你写的核心代码。','“The teammates handled execution”—your core code is absent from this caption.'),lines:[l('开局草稿：“这次主要由我带队，队友负责执行。感谢大家。”','Opening draft: “I led this win; the teammates handled execution. Thanks, everyone.”'),l('已知分工：许学长汇报与联络，小月设计，你和阿凯做代码。','Known work: Xu presented and coordinated; Yue designed; you and Kai coded.'),l('合照和文案都还没有发布。没有人已经替全队确认。','Neither the photo nor the caption has been posted. Nobody has approved for the whole team.')],source},
 'school-workload':{title:l('待分工任务','Unassigned work'),pressure:l('庆功还没结束，演示、海报、答辩三份活又被推到你面前。','Before dinner is over, the demo, poster and Q&A are all being pushed toward you.'),lines:[l('下一场展示：周五。','Next showcase: Friday.'),l('待分工：演示、海报、答辩准备。','Unassigned: demo, poster, Q&A preparation.'),l('小月和阿凯还没有答应分工。各自的时间与工作需要本人确认。','Yue and Kai have not accepted assignments. Each person must confirm their own time and work.')],source},

 'elevator-privacy':{title:l('走廊里的已知情况','What is known in the hallway'),pressure:l('离职只是猜测，谈话内容还没有公开。','Leaving is a guess. The conversation has not been shared.'),lines:[l('你刚从 HR 办公室出来。谈话内容未知。','You just left the HR office. The conversation is unknown.'),l('方经理、乔宁、程悦都在等电梯，都能听见。','Fang, Qiao and Cheng are waiting; all can hear.'),l('没有已知的离职计划、工资数字或工作调整。','No departure plan, pay figure or work change is established.')],source:{type:'original-fiction',path:'wiki/archive/specs/spec-3d-places.md#fiction'}},
 'elevator-blame':{title:l('演示事故 · 待核对','Demo incident · Unchecked'),pressure:l('账号打不开，原因还没查，归因已经要上报。','The account would not open. A cause is being reported before checking it.'),lines:[l('会议演示账号无法打开，会议提前结束。','The demo account would not open; the meeting ended early.'),l('交接记录：乔宁发送了演示链接与账号操作说明。完整性、日志与权限待核对。','Handoff note: Qiao sent the demo link and account instructions. Completeness, logs and permissions are unchecked.'),l('原因、责任归属与报告口径都未确认。','Cause, responsibility and the report wording are unconfirmed.')],source:{type:'original-fiction',path:'wiki/archive/specs/spec-3d-places.md#fiction'}},
 'office-overtime':{title:l('18:30 材料 · 待分工','18:30 material · Unassigned'),pressure:l('“顺手收尾”里，藏着三项还没分工的任务。','A “quick finish” hides three unassigned tasks.'),lines:[l('当前 17:50。客户希望 18:30 收到材料。','It is 17:50. The client wants material at 18:30.'),l('客户邮件：18:30 前提供主方案与数据摘要。','Client email: main proposal and data summary requested by 18:30.'),l('待确认：数据核对、排版、最终检查。','Unconfirmed: data checks, layout, final review.'),l('你、宁姐、瑞瑞的时间与负责范围都尚未确认。','Your, Ning’s and Rui’s availability and scope remain unconfirmed.')],source:{type:'original-fiction',path:'wiki/archive/specs/spec-3d-places.md#fiction'}},
 'office-interruption':{title:l('14:20 短会 · 待决定','14:20 meeting · Undecided'),pressure:l('方案还没讲完，“大家都懂了”已经替你说出口。','Your proposal is unfinished; someone says everyone already understands.'),lines:[l('轮到你讲方案，宁姐在关键点之前打断。','It is your slot; Ning interrupted before the key point.'),l('你的具体方案和风险由你说明。瑞瑞的数据尚未核对。','You explain your proposal and risk. Rui’s data is unchecked.'),l('何主管尚未作出正式决定，议程与方案都没有被自动修改。','He has not made a final decision. The agenda and proposal do not change automatically.')],source:{type:'original-fiction',path:'wiki/archive/specs/spec-3d-places.md#fiction'}},
};
