import type { Lang } from "@/data/taxonomy";
import { pick } from "@/lib/i18n";
import type { ModelIssue } from "./model-status";

export const M = {
  showKey: { zh: "显示密钥", en: "Show key" },
  hideKey: { zh: "隐藏密钥", en: "Hide key" },
  invalidAddress: { zh: "请填写完整的 http:// 或 https:// 地址。", en: "Enter a complete http:// or https:// address." },
  tokenParam: { zh: "Token 参数", en: "Token parameter" },
  title: { zh: "接入模型", en: "Connect a model" },
  intro: { zh: "填入你的 API Key，就能继续练习。", en: "Add your API key to continue practicing." },
  sharedUnavailableIntro: { zh: "默认模型暂时不可用。你可以填入自己的 API Key，继续练习。", en: "The default model is unavailable. Add your own API key to continue practicing." },
  checking: { zh: "正在检查模型连接…", en: "Checking the model connection…" },
  setup: { zh: "练习需要连接一个模型。", en: "Connect a model to start practicing." },
  credentials: { zh: "模型密钥已失效，请更新或换用自己的密钥。", en: "The model key is invalid. Update it or connect your own." },
  quota: { zh: "当前模型的额度已用完。补充额度或换用自己的密钥后，即可继续。", en: "The model’s credit has run out. Add credit or connect your own key to continue." },
  model: { zh: "模型配置不可用，请检查模型名称和连接设置。", en: "The model configuration is unavailable. Check its name and connection settings." },
  rate_limit: { zh: "请求有些频繁，稍等片刻再试。也可以接入自己的模型。", en: "Too many requests. Wait a moment and retry, or connect your own model." },
  service: { zh: "模型服务暂时不可用。可以稍后重试，或接入自己的模型。", en: "The model service is temporarily unavailable. Retry later or connect your own model." },
  network: { zh: "暂时连不上模型，请检查网络后重试。", en: "Cannot reach the model. Check your connection and retry." },
  browse: { zh: "场景、知识和已有记录仍可查看。", en: "You can still browse scenarios, lessons and saved practice." },
  retry: { zh: "重新检查", en: "Check again" },
  disabled: { zh: "接入可用的模型后继续", en: "Connect an available model to continue" },
  provider: { zh: "服务商", en: "Provider" },
  website: { zh: "获取 API Key ↗", en: "Get an API key ↗" },
  name: { zh: "模型名称", en: "Model name" },
  advanced: { zh: "其他设置", en: "More settings" },
  endpoint: { zh: "API 地址", en: "API address" },
  endpointHint: { zh: "使用兼容服务时填写；官方服务留空即可。", en: "For a compatible service. Leave blank for the official API." },
  reportModel: { zh: "复盘模型（可选）", en: "Review model (optional)" },
  sameModel: { zh: "默认使用上面的模型", en: "Uses the model above by default" },
  connect: { zh: "检查并保存", en: "Check and save" },
  free: { zh: "检查只读取模型信息，不生成内容。", en: "The check only reads model information; it generates no content." },
  privacy: { zh: "密钥仅保存在此设备，直接发送给服务商。", en: "Your key stays on this device and goes directly to the provider." },
  unverified: { zh: "该服务不支持连接检查，暂时无法确认是否可用。你可以保存，在下次练习时确认。", en: "This service cannot be verified through a metadata check. Save it and try it during your next practice." },
  saveAnyway: { zh: "保存并在练习中尝试", en: "Save and try in practice" },
  shared: { zh: "使用默认模型", en: "Use the default model" },
  pending: { zh: "接入模型后继续", en: "Continue after connecting a model" },
  connected: { zh: "已连接", en: "Connected" },
  unknown: { zh: "尚未确认", en: "Not yet verified" },
};
export const modelMessage = (issue: ModelIssue, lang: Lang) => pick(M[issue], lang);
