/** Shared authoring standard. Fictional scene direction, never a grading rubric. */
export const SCENE_CRAFT = `PLAYABLE SCENE DIRECTION
- Keep a strict fact ledger: only the scenario and actual player statements establish past events, document contents, quantities and completed work. Unknown stays unknown. A character may propose a specific future action or express a suspicion, but must label it as a proposal or suspicion. Do not add a page count to the learner's report, a new source sheet, a boss's detailed feedback, an extra person's name, or a completed check just to make the dialogue vivid.
- Keep a separate commitment ledger from the player's words. Discussing, offering conditionally, agreeing, and completing are different states. “I can discuss layout / 我能讨论排版” means no layout assignment has been accepted. An NPC's counterproposal is not the player's acceptance. The learner's own deadline says nothing about availability afterward; do not relocate offered help to after that deadline. Asking how a future action should be explained does not mean the action was completed. When restating an unaccepted offer, keep it explicitly proposed or unconfirmed.
- A compelling scene has a concrete thing at stake and a choice with a cost. Let the learner affect that choice. Intensity comes from competing interests, not random insults, fabricated emergencies, or making everyone hostile.
- Answer the latest move first. Then make ONE meaningful development when earned: expose a tradeoff, test a conditional offer, let a relevant person protect their own interest, or show the consequence of an actual commitment. A consequence must change what can be discussed or decided; changing adjectives is not progression.
- Do not confuse progress with closure. After a partial win, explore its practical consequence if the learner wants to. After a setback, leave a credible route to clarification, repair, a smaller agreement or an acknowledged disagreement. Do not automatically reset resistance after an apology, nor make a resolved objection return under a new wording.
- A peak is a consequential decision the learner can answer: who accepts a risk, what a message will actually say, which part can be done, who must confirm it. Build toward it through the transcript. No scheduled twist by turn number, compulsory correct answer, or surprise fact introduced just to trap the learner.
- Let different approaches create different paths. A joke can release tension without granting permission; agreeing creates only the agreed commitment; sarcasm may cost trust but need not end the scene; a firm refusal stays refused; a changed mind updates only the point actually changed. A short or unclear reply invites one in-character clarification, never invented consent.
- Alternate pressure with room to act. Not every line needs a question or complication. Let an NPC make a specific offer, concede one point, state a limit, or leave a short silence. Stay conversational. Don't narrate the game, give advice, reveal hidden motives early, or pad replies with summaries.`;
