import {test} from 'node:test';
import assert from 'node:assert/strict';
import {pick,scenarios} from '../../src/features/dinner/lib/content';
import {createWorld,PLAYER_HOME,roomContext} from '../../src/features/dinner/lib/room';
import {SaveSchema,opening,scriptedReply} from '../../src/features/dinner/lib/engine';
import {actorBeat,actionEvidence,chooseDrama,createDrama,dinnerContext,dinnerEvents,DramaSaveSchema,eventDialogue,playerBeat,readyForChoice,settleForSpeech,snapshotDrama,stepDrama,syncDrama,trophyPosition,validDinnerContext} from '../../src/features/dinner/lib/drama';
const advance=(d:ReturnType<typeof createDrama>,seconds:number,paused=false)=>{for(let i=0;i<Math.ceil(seconds/.05);i++)stepDrama(d,.05,paused);};

test('later moments require an explicit narrative invitation, never a fixed turn number',()=>{
 for(const scene of scenarios){const d=createDrama();syncDrama(d,scene,0,false,false);assert.equal(d.active,undefined);syncDrama(d,scene,0,true,false);assert.equal(d.seen.length,1);settleForSpeech(d);for(let turn=1;turn<=12;turn++)syncDrama(d,scene,turn,true,false);assert.equal(d.seen.length,1);const later=dinnerEvents.find(e=>e.scene===scene.id&&e.turn===2)!;syncDrama(d,scene,6,true,false,{requestedEvent:later.id});assert.equal(d.active,later.id);settleForSpeech(d);syncDrama(d,scene,7,true,false,{requestedEvent:later.id});assert.equal(d.seen.length,2);const finished=createDrama();syncDrama(finished,scene,0,true,true);assert.equal(finished.active,undefined);}
});
test('the leader raises first, others follow, then look toward the player',()=>{
 const d=createDrama();syncDrama(d,scenarios[0],0,true,false);advance(d,.5);assert.ok(actorBeat(d,0,'work').raise>.8);assert.equal(actorBeat(d,1,'work').raise,0);assert.equal(actorBeat(d,2,'work').raise,0);assert.equal(actorBeat(d,1,'work').gaze,0);advance(d,2);for(let i=0;i<3;i++){assert.equal(actorBeat(d,i,'work').raise,1);assert.equal(actorBeat(d,i,'work').gaze,-1);}
});
test('choosing preserves cup continuity and never makes the player drink',()=>{
 const d=createDrama(),world=createWorld(scenarios[0]);syncDrama(d,scenarios[0],0,true,false);advance(d,3);const before=actorBeat(d,0,'work').raise;chooseDrama(d,'join',world,0);assert.equal(actorBeat(d,0,'work').raise,before);advance(d,1);assert.ok(playerBeat(d).raise>.99);assert.equal('sip' in playerBeat(d),false);assert.equal(d.inventory,'glass');advance(d,4);assert.equal(d.phase,'settled');assert.equal(actorBeat(d,0,'work').raise,0);assert.equal(d.records.length,1);assert.equal(chooseDrama(d,'tea',world,0),false);
});
test('a declined toast lowers bystanders first, with no forced drinking or timeout choice',()=>{
 const d=createDrama(),world=createWorld(scenarios[0]);syncDrama(d,scenarios[0],0,true,false);advance(d,20);assert.equal(d.phase,'waiting');assert.equal(d.records.length,0);assert.equal(eventDialogue(d,'zh')!.text,pick(dinnerEvents[0].line,'zh'));chooseDrama(d,'hold',world,0);advance(d,2);assert.equal(actorBeat(d,1,'work').raise,0);assert.equal(actorBeat(d,0,'work').raise,1);assert.equal(actorBeat(d,0,'work').sip,0);assert.equal(d.inventory,'none');
});
test('typing, explicit pause and pending approaches preserve the moment; deliberate action resumes it',()=>{
 const d=createDrama(),world=createWorld(scenarios[0]);syncDrama(d,scenarios[0],0,true,false);advance(d,1);const before=d.elapsed;advance(d,4,true);assert.equal(d.elapsed,before);d.paused=true;advance(d,4);assert.equal(d.elapsed,before);d.paused=false;d.pending='tea';advance(d,4);assert.equal(d.elapsed,before);d.pending=undefined;d.paused=true;chooseDrama(d,'tea',world,0);assert.equal(d.paused,false);advance(d,1);assert.ok(playerBeat(d).raise>.99);
});
test('cups and a passed phone require physical proximity before evidence or inventory changes',()=>{
 const work=scenarios[0],world=createWorld(work),d=createDrama();syncDrama(d,work,0,true,false);world.player.seated=false;world.player.x=4.5;world.player.z=5;assert.equal(readyForChoice(d,'tea',world),false);assert.equal(chooseDrama(d,'tea',world,0),false);assert.deepEqual(d.records,[]);assert.equal(d.inventory,'none');Object.assign(world.player,PLAYER_HOME);assert.equal(chooseDrama(d,'tea',world,0),true);world.player.x=4.5;world.player.z=5;assert.equal(readyForChoice(d,'tea',world),true);
 const family=scenarios[1],familyWorld=createWorld(family),phone=createDrama();syncDrama(phone,family,0,true,false);settleForSpeech(phone);syncDrama(phone,family,2,true,false,{requestedEvent:'family-phone'});assert.equal(readyForChoice(phone,'accept',familyWorld),false);assert.equal(chooseDrama(phone,'accept',familyWorld,2),false);familyWorld.player.seated=false;familyWorld.player.x=familyWorld.npcs[1].x-1.5;familyWorld.player.z=familyWorld.npcs[1].z;phone.inventory='tea';assert.equal(readyForChoice(phone,'accept',familyWorld),false);assert.equal(chooseDrama(phone,'accept',familyWorld,2),false);assert.equal(phone.inventory,'tea');phone.inventory='none';assert.equal(chooseDrama(phone,'accept',familyWorld,2),true);assert.equal(phone.inventory,'phone');assert.equal(phone.records[0].posture,'standing');
});
test('all eighteen physical choices produce bilingual resistant replies and observed-action evidence',()=>{
 for(const scene of scenarios)for(const event of dinnerEvents.filter(e=>e.scene===scene.id))for(const choice of event.choices){const d=createDrama(),world=createWorld(scene);d.active=event.id;d.seen=[event.id];d.phase='waiting';if(choice.id==='accept'){world.player.seated=false;world.player.x=world.npcs[1].x-1.5;world.player.z=world.npcs[1].z;}assert.ok(chooseDrama(d,choice.id,world,event.turn));for(const lang of ['zh','en'] as const){const evidence=actionEvidence(d.records[0],lang);assert.equal(evidence.action,pick(choice.label,lang));assert.equal(eventDialogue(d,lang),undefined);assert.equal(evidence.reply,undefined);const context=dinnerContext(d)!;assert.equal(validDinnerContext(context,scene.id),true);const response=scriptedReply(scene,lang==='zh'?'嗯':'Hmm',event.turn+1,lang,roomContext(world),context);assert.notEqual(response.text,scriptedReply(scene,lang==='zh'?'嗯':'Hmm',event.turn+1,lang,roomContext(world)).text);}assert.equal(DramaSaveSchema.safeParse(snapshotDrama(d)).success,true);}
});
test('refresh preserves actual actions; impossible scene, phase and fabricated action evidence fail',()=>{
 const scene=scenarios[0],d=createDrama(),world=createWorld(scene);syncDrama(d,scene,0,true,false);chooseDrama(d,'tea',world,0);const saved={version:1,scenarioId:scene.id,lang:'zh',started:true,complete:false,draft:'原话',messages:[opening(scene,'zh')],dinner:snapshotDrama(d)};assert.equal(SaveSchema.parse(JSON.parse(JSON.stringify(saved))).dinner?.inventory,'tea');assert.equal(SaveSchema.safeParse({...saved,scenarioId:'school',messages:[opening(scenarios[2],'zh')]}).success,false);assert.equal(DramaSaveSchema.safeParse({...d,records:[]}).success,false);assert.equal(DramaSaveSchema.safeParse({...d,pending:'hold'}).success,false);assert.equal(DramaSaveSchema.safeParse({...d,phase:'waiting'}).success,false);assert.equal(validDinnerContext({...dinnerContext(d)!,previous:[]},'work'),false);settleForSpeech(d);assert.equal(eventDialogue(d,'zh'),undefined);assert.equal(d.records.length,1);
});
test('trophy moves toward the captain only once dinner begins and returns to the center for a team photo',()=>{
 const d=createDrama(),scene=scenarios[2],world=createWorld(scene);assert.deepEqual(trophyPosition(d),{x:0,z:-.75});syncDrama(d,scene,0,true,false);assert.equal(trophyPosition(d).z,-1.85);settleForSpeech(d);syncDrama(d,scene,2,true,false,{requestedEvent:'school-photo'});chooseDrama(d,'group',world,2);assert.deepEqual(trophyPosition(d),{x:0,z:0});
});
test('per-utterance physical evidence cannot be changed by later choices or mutable world state',()=>{
 const d=createDrama(),scene=scenarios[2],world=createWorld(scene);syncDrama(d,scene,0,true,false);chooseDrama(d,'hold',world,0);const spoken=dinnerContext(d)!;settleForSpeech(d);syncDrama(d,scene,2,true,false,{requestedEvent:'school-photo'});world.player.seated=false;world.player.x=4.5;world.player.z=5;assert.equal(chooseDrama(d,'group',world,2),false);assert.equal(d.records.length,1);Object.assign(world.player,PLAYER_HOME);world.player.seated=true;chooseDrama(d,'group',world,2);assert.equal(d.records.length,2);assert.equal(spoken.previous.length,1);assert.equal(spoken.choice,'hold');assert.equal(spoken.previous[0].posture,'seated');assert.equal(validDinnerContext(spoken,'school'),true);
});
